### ISSUE TITLE
How do you deploy the `age` Private Key?

### ISSUE THREAD

**Issue by LucianU** [Mic92/dotfiles#554]
If my understanding is correct, the `age` Private Key is used to decrypt the secrets. This means it needs to be on the deployed system. Is this right?

If so, how do you deploy the key? Do you do it manually?

**Comment by Mic92** [comment]
My servers have a ssh host key at `/etc/ssh/ssh_host_ed25519_key` each from which the age key is derived at activation time of a new nixos profile: https://github.com/Mic92/sops-nix#supported-encryption-methods
