### ISSUE TITLE
Question about home-manager

### ISSUE THREAD

**Issue by lutzgo** [Mic92/dotfiles#737]
Hey @Mic92,
you have got an interesting and complex nix-setup. I forked to fiddle around with it and stumbled over your home-manager setup. Can you give me a hint, how it works? I would like to invoke it with a regular nixos-rebuild and just can not wrap my head around your setup. As I am **always** willing to learn, your answer would be very much appreciated.

**Comment by Mic92** [comment]
So the entry point is a function in my zshrc here: https://github.com/Mic92/dotfiles/blob/7c194d124534dc94c70361934f38cf29f6668ffc/home/.zshrc#L176

I run hm and it will run this script: https://github.com/Mic92/dotfiles/blob/7c194d124534dc94c70361934f38cf29f6668ffc/home-manager/flake-module.nix#L26

The script will use the hostname of the machine its running on to find the right home-manager configuration for the system in my flake. All my home-manager profiles are located in the same file: https://github.com/Mic92/dotfiles/blob/main/home-manager/flake-module.nix#L26

I hope this answers your question.

**Comment by tom-tubeless** [comment]
@Mic92 thank you, that answers my question perfectly.
