### ISSUE TITLE
Question: Folder-based secrets organization with sops

### ISSUE THREAD

**Issue by oneingan** [Mic92/dotfiles#938]
Hi, i recently observed how you are organizing secrets in `/sops` folder and I loved it. But some questions arise on me, how are you consuming that? I tried to find it in your code but I haven't found it. 

I was, also, wondering if a module system like [haumea](https://github.com/nix-community/haumea) could make it accessible to `sops-nix` or similar?

Thanks in advance from a follower of your amazing work!!

**Comment by Mic92** [comment]
We are working on a new NixOS fleet management tool that unifies installation, deployment, secrets and some abstractions to allow also non-technical users. This folder based secret management is part of it: https://git.clan.lol/clan/clan-core/src/branch/main/docs/secrets-management.md

**Comment by oneingan** [comment]
Thanks for your reply, I was taking a look and looks great. Do you imagine how to factorize out the secrets part as a standalone tool with a nixosModule? Would it makes sense to you? Regards.

**Comment by Mic92** [comment]
I thought about it, but I don't when and if I get to do that.
